[toolchain]
channel = "1.87.0"
# this should be kept in sync with xtask
targets = [
    "aarch64-unknown-linux-gnu",
    "i586-unknown-linux-gnu",
    "i686-unknown-linux-gnu",
    "s390x-unknown-linux-gnu",
    "wasm32-wasip1",
    "x86_64-unknown-linux-gnu",
    "x86_64-unknown-none",
]
