[package]
name = "chacha8rand"
version = "0.1.0"
edition = "2021"

[[bench]]
name = "raw_throughput"
harness = false

[dependencies]
arrayref = "0.3.9"
wide = "0.7.28"

[dev-dependencies]
divan = "0.1.14"
