[package]
name = "chacha8rand"
version = "0.1.0"
edition = "2021"

[features]
default = []
rand_core_0_6 = ["dep:rand_core"]
std = []
unstable_internals = []

[dependencies]
arrayref = "0.3.9"
rand_core = { version = "0.6.4", default-features = false, optional = true }
