[package]
name = "benchmarks"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
chacha8rand = { path = "../chacha8rand", features = ["std", "unstable_internals"] }
rand_core = "0.6"
rand_chacha = "0.3"
