[package]
name = "benchmarks"
version = "0.1.0"
edition = "2021"
publish = false
license = "MIT OR Apache-2.0"

[dependencies]
chacha8rand = { path = "../chacha8rand", features = ["std", "rand_core_0_9"] }
rand_core = "0.9"
rand_chacha = "0.9"
